# Generated by Django 5.1.5 on 2025-02-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.FloatField()),
                ('endereco', models.CharField(max_length=100)),
                ('contato', models.FloatField()),
                ('historicodeagendamento', models.CharField(max_length=100)),
                ('designerdeunha', models.CharField(max_length=100)),
            ],
        ),
    ]
